# Generated by Django 4.0.3 on 2022-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=100)),
                ('time', models.TimeField(blank=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
