# Generated by Django 4.0.3 on 2022-05-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
