# Generated by Django 4.0.4 on 2022-05-17 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birth_certificate', '0002_remove_personaldata_id_personaldata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('token', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
